#I write this program by myself. Sign here:羅瑋翔
#Email Address:xianglo9121.mg10@nycu.edu.tw
#Anything Special? pic3 and pic4 are special
#None
def drawTriangle(myTurtle,side):
    myTurtle.up()
    myTurtle.left(90)
    myTurtle.forward(150)
    myTurtle.left(90)
    myTurtle.forward(150)
    myTurtle.down()
    myTurtle.left(60)
    myTurtle.forward(side)
    myTurtle.left(120)
    myTurtle.forward(side)
    myTurtle.left(120)
    myTurtle.forward(side)
    
def drawTrapezoid(myTurtle,side1,side2):
    myTurtle.up()
    myTurtle.left(90)
    myTurtle.forward(150)
    myTurtle.right(90)
    myTurtle.forward(side1)
    myTurtle.down()
    myTurtle.pencolor("green")
    myTurtle.forward(side1)
    myTurtle.right(60)
    myTurtle.forward(side1)
    myTurtle.right(120)
    myTurtle.forward(side2)
    myTurtle.right(120)
    myTurtle.forward(side1)

def drawArrow(myTurtle,side1,side2,side3):
    myTurtle.up()
    myTurtle.right(90)
    myTurtle.forward(200)
    myTurtle.right(90)
    myTurtle.forward(150)
    myTurtle.down()
    myTurtle.pencolor("blue")
    myTurtle.forward(side1)
    myTurtle.left(90)
    myTurtle.forward(side1)
    myTurtle.left(90)
    myTurtle.forward(side1)
    myTurtle.right(90)
    myTurtle.forward(side2)
    myTurtle.left(120)
    myTurtle.forward(side3)
    myTurtle.left(120)
    myTurtle.forward(side3)
    myTurtle.left(120)
    myTurtle.forward(side2)

def drawCross(myTurtle,side):
    myTurtle.up()
    myTurtle.right(90)
    myTurtle.forward(150)
    myTurtle.left(90)
    myTurtle.forward(125)
    myTurtle.down()
    myTurtle.pencolor("red")
    myTurtle.forward(side)
    myTurtle.right(90)
    myTurtle.forward(side)
    myTurtle.left(90)
    myTurtle.forward(side)
    myTurtle.right(90)
    myTurtle.forward(side)
    myTurtle.right(90)
    myTurtle.forward(side)
    myTurtle.left(90)
    myTurtle.forward(side)
    myTurtle.right(90)
    myTurtle.forward(side)
    myTurtle.right(90)
    myTurtle.forward(side)
    myTurtle.left(90)
    myTurtle.forward(side)
    myTurtle.right(90)
    myTurtle.forward(side)
    myTurtle.right(90)
    myTurtle.forward(side)
    myTurtle.left(90)
    myTurtle.forward(side)
    
import turtle
t1=turtle.Turtle()
t2=turtle.Turtle()
t3=turtle.Turtle()
t4=turtle.Turtle()
drawTriangle(t1,150)
drawTrapezoid(t2,100,200)
drawArrow(t3,50,25,100)
drawCross(t4,50)
